/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ltlogic.constants;

/**
 *
 * @author Hoang
 */
public enum CountryEnum {

    AD(0, "Andorra"),
    AE(1, "United Arab Emirates"),
    AF(2, "Afghanistan"),
    AG(3, "Antigua and Barbuda"),
    AI(4, "Anguilla"),
    AL(5, "Albania"),
    AM(6, "Armenia"),
    AN(7, "Netherlands Antilles"),
    AO(8, "Angola"),
    AQ(9, "Antarctica"),
    AR(10, "Argentina"),
    AS(11, "American Samoa"),
    AT(12, "Austria"),
    AU(13, "Australia"),
    AW(14, "Aruba"),
    AX(15, "Åland Islands"),
    AZ(16, "Azerbaijan"),
    BA(17, "Bosnia and Herzegovina"),
    BB(18, "Barbados"),
    BD(19, "Bangladesh"),
    BE(20, "Belgium"),
    BF(21, "Burkina Faso"),
    BG(22, "Bulgaria"),
    BH(23, "Bahrain"),
    BI(24, "Burundi"),
    BJ(25, "Benin"),
    BL(26, "Saint Barthélemy"),
    BM(27, "Bermuda"),
    BN(28, "Brunei"),
    BO(29, "Bolivia"),
    BQ(30, "Bonaire, Sint Eustatius and Saba"),
    BR(31, "Brazil"),
    BS(32, "Bahamas"),
    BT(33, "Bhutan"),
    BV(34, "Bouvet Island"),
    BW(35, "Botswana"),
    BY(36, "Belarus"),
    BZ(37, "Belize"),
    CA(38, "Canada"),
    CC(39, "Cocos Islands"),
    CD(40, "The Democratic Republic Of Congo"),
    CF(41, "Central African Republic"),
    CG(42, "Congo"),
    CH(43, "Switzerland"),
    CI(44, "Côte d'Ivoire"),
    CK(45, "Cook Islands"),
    CL(46, "Chile"),
    CM(47, "Cameroon"),
    CN(48, "China"),
    CO(49, "Colombia"),
    CR(50, "Costa Rica"),
    CU(51, "Cuba"),
    CV(52, "Cape Verde"),
    CW(53, "Curaçao"),
    CX(54, "Christmas Island"),
    CY(55, "Cyprus"),
    CZ(56, "Czech Republic"),
    DE(57, "Germany"),
    DJ(58, "Djibouti"),
    DK(59, "Denmark"),
    DM(60, "Dominica"),
    DO(61, "Dominican Republic"),
    DZ(62, "Algeria"),
    EC(63, "Ecuador"),
    EE(64, "Estonia"),
    EG(65, "Egypt"),
    EH(66, "Western Sahara"),
    ER(67, "Eritrea"),
    ES(68, "Spain"),
    ET(69, "Ethiopia"),
    FI(70, "Finland"),
    FJ(71, "Fiji"),
    FK(72, "Falkland Islands"),
    FM(73, "Micronesia"),
    FO(74, "Faroe Islands"),
    FR(75, "France"),
    GA(76, "Gabon"),
    GB(77, "United Kingdom"),
    GD(78, "Grenada"),
    GE(79, "Georgia"),
    GF(80, "French Guiana"),
    GG(81, "Guernsey"),
    GH(82, "Ghana"),
    GI(83, "Gibraltar"),
    GL(84, "Greenland"),
    GM(85, "Gambia"),
    GN(86, "Guinea"),
    GP(87, "Guadeloupe"),
    GQ(88, "Equatorial Guinea"),
    GR(89, "Greece"),
    GS(90, "South Georgia And The South Sandwich Islands"),
    GT(91, "Guatemala"),
    GU(92, "Guam"),
    GW(93, "Guinea-Bissau"),
    GY(94, "Guyana"),
    HK(95, "Hong Kong"),
    HM(96, "Heard Island And McDonald Islands"),
    HN(97, "Honduras"),
    HR(98, "Croatia"),
    HT(99, "Haiti"),
    HU(100, "Hungary"),
    ID(101, "Indonesia"),
    IE(102, "Ireland"),
    IL(103, "Israel"),
    IM(104, "Isle Of Man"),
    IN(105, "India"),
    IO(106, "British Indian Ocean Territory"),
    IQ(107, "Iraq"),
    IR(108, "Iran"),
    IS(109, "Iceland"),
    IT(110, "Italy"),
    JE(111, "Jersey"),
    JM(112, "Jamaica"),
    JO(113, "Jordan"),
    JP(114, "Japan"),
    KE(115, "Kenya"),
    KG(116, "Kyrgyzstan"),
    KH(117, "Cambodia"),
    KI(118, "Kiribati"),
    KM(119, "Comoros"),
    KN(120, "Saint Kitts And Nevis"),
    KP(121, "North Korea"),
    KR(122, "South Korea"),
    KW(123, "Kuwait"),
    KY(124, "Cayman Islands"),
    KZ(125, "Kazakhstan"),
    LA(126, "Laos"),
    LB(127, "Lebanon"),
    LC(128, "Saint Lucia"),
    LI(129, "Liechtenstein"),
    LK(130, "Sri Lanka"),
    LR(131, "Liberia"),
    LS(132, "Lesotho"),
    LT(133, "Lithuania"),
    LU(134, "Luxembourg"),
    LV(135, "Latvia"),
    LY(136, "Libya"),
    MA(137, "Morocco"),
    MC(138, "Monaco"),
    MD(139, "Moldova"),
    ME(140, "Montenegro"),
    MF(141, "Saint Martin"),
    MG(142, "Madagascar"),
    MH(143, "Marshall Islands"),
    MK(144, "Macedonia"),
    ML(145, "Mali"),
    MM(146, "Myanmar"),
    MN(147, "Mongolia"),
    MO(148, "Macao"),
    MP(149, "Northern Mariana Islands"),
    MQ(150, "Martinique"),
    MR(151, "Mauritania"),
    MS(152, "Montserrat"),
    MT(153, "Malta"),
    MU(154, "Mauritius"),
    MV(155, "Maldives"),
    MW(156, "Malawi"),
    MX(157, "Mexico"),
    MY(158, "Malaysia"),
    MZ(159, "Mozambique"),
    NA(160, "Namibia"),
    NC(161, "New Caledonia"),
    NE(162, "Niger"),
    NF(163, "Norfolk Island"),
    NG(164, "Nigeria"),
    NI(165, "Nicaragua"),
    NL(166, "Netherlands"),
    NO(167, "Norway"),
    NP(168, "Nepal"),
    NR(169, "Nauru"),
    NU(170, "Niue"),
    NZ(171, "New Zealand"),
    OM(172, "Oman"),
    PA(173, "Panama"),
    PE(174, "Peru"),
    PF(175, "French Polynesia"),
    PG(176, "Papua New Guinea"),
    PH(177, "Philippines"),
    PK(178, "Pakistan"),
    PL(179, "Poland"),
    PM(180, "Saint Pierre And Miquelon"),
    PN(181, "Pitcairn"),
    PR(182, "Puerto Rico"),
    PS(183, "Palestine"),
    PT(184, "Portugal"),
    PW(185, "Palau"),
    PY(186, "Paraguay"),
    QA(187, "Qatar"),
    RE(188, "Reunion"),
    RO(189, "Romania"),
    RS(190, "Serbia"),
    RU(191, "Russia"),
    RW(192, "Rwanda"),
    SA(193, "Saudi Arabia"),
    SB(194, "Solomon Islands"),
    SC(195, "Seychelles"),
    SD(196, "Sudan"),
    SE(197, "Sweden"),
    SG(198, "Singapore"),
    SH(199, "Saint Helena"),
    SI(200, "Slovenia"),
    SJ(201, "Svalbard And Jan Mayen"),
    SK(202, "Slovakia"),
    SL(203, "Sierra Leone"),
    SM(204, "San Marino"),
    SN(205, "Senegal"),
    SO(206, "Somalia"),
    SR(207, "Suriname"),
    SS(208, "South Sudan"),
    ST(209, "Sao Tome And Principe"),
    SV(210, "El Salvador"),
    SX(211, "Sint Maarten (Dutch part),"),
    SY(212, "Syria"),
    SZ(213, "Swaziland"),
    TC(214, "Turks And Caicos Islands"),
    TD(215, "Chad"),
    TF(216, "French Southern Territories"),
    TG(217, "Togo"),
    TH(218, "Thailand"),
    TJ(219, "Tajikistan"),
    TK(220, "Tokelau"),
    TL(221, "Timor-Leste"),
    TM(222, "Turkmenistan"),
    TN(223, "Tunisia"),
    TO(224, "Tonga"),
    TR(225, "Turkey"),
    TT(226, "Trinidad and Tobago"),
    TV(227, "Tuvalu"),
    TW(228, "Taiwan"),
    TZ(229, "Tanzania"),
    UA(230, "Ukraine"),
    UG(231, "Uganda"),
    UM(232, "United States Minor Outlying Islands"),
    US(233, "United States"),
    UY(234, "Uruguay"),
    UZ(235, "Uzbekistan"),
    VA(236, "Vatican"),
    VC(237, "Saint Vincent And The Grenadines"),
    VE(238, "Venezuela"),
    VG(239, "British Virgin Islands"),
    VI(240, "U.S. Virgin Islands"),
    VN(241, "Vietnam"),
    VU(242, "Vanuatu"),
    WF(243, "Wallis And Futuna"),
    WS(244, "Samoa"),
    YE(245, "Yemen"),
    YT(246, "Mayotte"),
    ZA(247, "South Africa"),
    ZM(248, "Zambia"),
    ZW(249, "Zimbabwe");

    private final int id;
    private final String desc;

    private CountryEnum(int id, String desc) {
        this.id = id;
        this.desc = desc;
    }

    public int getCountryEnumId() {
        return id;
    }

    public String getCountryEnumDesc() {
        return desc;
    }

    public static CountryEnum getCountryEnumById(int id) {
        for (CountryEnum rel : CountryEnum.values()) {
            if (rel.getCountryEnumId() == id) {
                return rel;
            }
        }
        return null;
    }

}
